spring:
  datasource:
    url: jdbc:mariadb://librarymusik.synology.me:3306/PEMDB
#    url: jdbc:mariadb://hongikcenas.synology.me:3307/PEMDB
    driver-class-name: org.mariadb.jdbc.Driver
    username: PEMDB
    password: "@T806T817t818"
#    나중에 암호화해서 올릴것
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace
